Hotel.App/Models/ViewModels/ReviewCommentViewModel.cs
namespace Hotel.App.Models.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class ReviewCommentViewModel
    {
        [Required]
        [MinLength(10, ErrorMessage = "Коментарът трябва да е дълъг поне 10 символа")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }   

        [Required]
        public int ReviewId { get; set; }
    }
}

Hotel.App/Controllers/AppointmentController.cs
namespace Hotel.App.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Hotel.Models;
    using Models.ViewModels;
    using AutoMapper;
    using System.Net.Mail;
    using System.Threading.Tasks;
    using Utils;

    public class AppointmentController : BaseController
    {
        public AppointmentController(IHotelData data)
            : base(data)
        {
        }


        public ActionResult Index()
        {
            var appointments = this.Data.Appointments.All().ToList();

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(AppointmentViewModel appointmentModel)
        {
            if (this.ModelState.IsValid)
            {
                this.ViewBag.IsDisabled = "disabled";

                var appointment = Mapper.Map<Appointment>(appointmentModel);

                this.Data.Appointments.Add(appointment);
                this.Data.SaveChanges();


                var message = new MailMessage();
                var toEmail = XmlHelper.GetNode("LeadsEmail");
                message.To.Add(new MailAddress(toEmail));
                message.Subject = "Имейл за резервация от Крапец Холидей";
                message.Body = this.FillClientInfo(appointmentModel);
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }

                this.TempData["message"] = @"Резервацията Ви е изпратена успешно!
                                             Ще се свържем с Вас до 2 работни часа за потвърждение!";
                return this.View();
            }

            return this.View(appointmentModel);
        }

        private string FillClientInfo(AppointmentViewModel model)
        {
            var template = System.IO.File.ReadAllText(this.Server.MapPath("~/Files/Templates/AppointmentEmailTemplate.html"));
            template = template.Replace("[TEMPLATE_NAME]", model.FirstName).
            Replace("[TEMPLATE_LAST_NAME]", model.LastName).
            Replace("[TEMPLATE_EMAIL]", model.Email).
            Replace("[TEMPLATE_PHONE]", model.Phone).
            Replace("[TEMPLATE_START_DATE]", model.StartDate.ToString("dd.MM.yyyy")).
            Replace("[TEMPLATE_END_DATE]", model.EndDate.ToString("dd.MM.yyyy")).
            Replace("[TEMPLATE_COUNT]", model.HosesCount.ToString());

            return template;
        }
    }
}

Hotel.App/Controllers/ContactUsController.cs
namespace Hotel.App.Controllers
{
    using System.Net;
    using System.Net.Mail;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using AutoMapper;
    using Hotel.Models;
    using Utils;

    public class ContactUsController : BaseController
    {
        public ContactUsController(IHotelData data) 
            : base(data)
        {
        }

        // GET: ContactUs
        public ActionResult Index()
        {
            return this.View();
        }        

        // GET: ContactUs/Create
        public ActionResult Create()
        {
            string currentUserUsername = null;
            string currentUserEmail = null;
            
            if (this.UserProfile != null)
            {
                currentUserEmail = this.UserProfile.Email;
                currentUserUsername = this.UserProfile.UserName;
            }

            return this.PartialView("_Email", new EmailViewModel {Name = currentUserUsername, EmailAddress = currentUserEmail});
        }

        // POST: ContactUs/Create       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(EmailViewModel email)
        {
            if (this.ModelState.IsValid)
            {
                var dataEmail = Mapper.Map<Email>(email);

                this.Data.Emails.Add(dataEmail);
                this.Data.SaveChanges();

                var message = new MailMessage();
                var toEmail = XmlHelper.GetNode("LeadsEmail");
                message.To.Add(new MailAddress(toEmail));
                message.Subject = "Имейл изпратен от контактната форма на Крапетц Холидей";
                message.Body = email.Content;
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }

                return this.JavaScript("sendEmailSuccessfully()");
            }

            return this.PartialView("_Email", email);
        }
    }
}

Hotel.App/Controllers/GalleryController.cs
namespace Hotel.App.Controllers
{
    using System.Web.Mvc;
    using Data.UnitOfWork;

    public class GalleryController : BaseController
    {
        public GalleryController(IHotelData data) : base(data)
        {
        }

        // GET: Gallery
        public ActionResult Index()
        {
            return this.View();
        }
    }
}

Hotel.App/Controllers/ReviewsController.cs
namespace Hotel.App.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using AutoMapper;
    using Data.UnitOfWork;
    using Hotel.Models;
    using Models.ViewModels;

    public class ReviewsController : BaseController
    {
        public ReviewsController(IHotelData data)
            : base(data)
        {
        }

        // GET: Reviews
        public ActionResult Index(int page = 1, int count = 5)
        {
            var allReviews = this.Data.Reviews.All().Where(r => r.IsPublished).Include(r => r.Comments).Include(r => r.Author);
            var reviews = allReviews
                .OrderByDescending(r => r.CreationDate)
                .Skip((page - 1) * count)
                .Take(count)
                .ToList();

            int reviewsCount = allReviews.Count();
            this.ViewBag.TotalPages = (reviewsCount + count - 1) / count;
            this.ViewBag.CurrentPage = page;

            var vmReviews = Mapper.Map<IEnumerable<Review>, IEnumerable<ReviewVewModel>>(reviews);

            return this.View(vmReviews);
        }

        // GET: Reviews/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Review review = this.Data.Reviews.Find(id);
            if (review == null)
            {
                return this.HttpNotFound();
            }

            return this.View(review);
        }

        // GET: Reviews/Create
        [Authorize]
        public ActionResult Create()
        {
            return this.View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,Rating")] Review review)
        {
            if (this.ModelState.IsValid)
            {
                review.Author = this.UserProfile;
                review.CreationDate = DateTime.Now;
                review.IsPublished = false;

                this.Data.Reviews.Add(review);
                this.Data.SaveChanges();
                return this.RedirectToAction("Index");
            }

            return this.View(review);
        }

        // GET: Reviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = this.Data.Reviews.Find(id);
            if (review == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return this.View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content,CreationDate")] Review review)
        {
            if (this.ModelState.IsValid)
            {
                this.Data.Reviews.Update(review);
                this.Data.SaveChanges();
                return this.RedirectToAction("Index");
            }

            return this.View(review);
        }

        // GET: Reviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Review review = this.Data.Reviews.Find(id);
            if (review == null)
            {
                return this.HttpNotFound();
            }

            return this.View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Review review = this.Data.Reviews.Find(id);
            review.IsPublished = false;
            this.Data.Reviews.Update(review);
            this.Data.SaveChanges();

            return this.RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComment([Bind(Include = "Content, ReviewId")] ReviewCommentViewModel comment)
        {
            var review = this.Data.Reviews.Find(comment.ReviewId);
            var reviewComment = new ReviewComment();

            if (this.ModelState.IsValid)
            {
                reviewComment.Content = comment.Content;
                reviewComment.Author = this.UserProfile;
                reviewComment.CreationTime = DateTime.Now;
                reviewComment.Review = review;
                reviewComment.IsPublished = false;

                this.Data.Comments.Add(reviewComment);
                this.Data.SaveChanges();

                return this.RedirectToAction("/Details/" + comment.ReviewId);
            }

            return this.View("Details", review);
        }
    }
}

Hotel.App/Views/Shared/_Layout.cshtml
@using Hotel.App.Utils
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Крапетц Холидей</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="header">
        <div class="header-section">
            <div class="container">
                <div class="row">
                    <div class="header-container-left col-sm-4 col-md-4">
                        <div class="reviews-container">
                            <h3 class="site-title">Крапец Холидей</h3>
                            <span class="review-stars" title="@Session["AverageRating"] среден рейтинг">
                                @for (int i = 0; i < double.Parse(Session["AverageRating"].ToString()); i++)
                                {
                                    <img src="~/Files/Images/star-icon.png" alt="star icon" />
                                }
                            </span>
                            <a href="/Reviews/Index" title="Виж всички отзиви">@Session["ReviewsCount"] отзиви</a>
                        </div>
                    </div>
                    <div class="header-container-middle col-sm-4 col-md-4">
                        <a href="/Home/Index" title="Начало"><img src="~/Files/Images/logo.png" alt="Krapets Holiday Logo" class="site-logo" /></a>
                    </div>
                    <div class="header-container-right col-sm-4 col-md-4  text-right">
                        <div class="header-location">
                            <p>село Крапец</p>
                            <a href="tel:@XmlHelper.GetNode("PhoneNumber")">тел: @XmlHelper.GetNode("PhoneNumber").BeautifyPhoneNumber()</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="navigation-section">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navigation">
                        <span class="icon-bar first-bar"></span>
                        <span class="icon-bar second-bar"></span>
                        <span class="icon-bar third-bar"></span>
                    </button>
                </div>
                <div class="navigation navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Начало", "Index", "Home")</li>
                        <li>@Html.ActionLink("Галерия", "Index", "Gallery")</li>
                        <li>@Html.ActionLink("Отзиви", "Index", "Reviews")</li>
                        <li>@Html.ActionLink("Резервация", "Index", "Appointment")</li>
                        <li>@Html.ActionLink("Контакти", "Index", "ContactUs")</li>
                       @if (User.IsInRole("Admin"))
                       {
                        <li>@Html.ActionLink("Контролен панел", "Index", "ControlPanel")</li>
                       }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>

    <div class="wrapper">
        @RenderSection("slideshow", required: false)
        <div class="container body-content">
            @Html.Partial("~/Views/Shared/_Messages.cshtml")
            @RenderBody()
        </div>
        @RenderSection("googlemap", required: false)
        <div class="push"></div>
    </div>

    <footer>
        <div class="footer-section-top">
            <div class="container">
                <div class="row">
                    <div class="footer-container-left col-sm-4 col-md-4">
                        <div class="social-icons">
                            <a href="@XmlHelper.GetNode("FacebookUrl")" target="_blank" class="facebook-icon"></a>
                            <a href="@XmlHelper.GetNode("GooglePlusUrl")" target="_blank" class="google-icon"></a>
                        </div>
                    </div>
                    <div class="footer-container-middle col-sm-4 col-md-4">
                        <a href="/Home/Index"><img src="~/Files/Images/logo.png" alt="Krapets Holiday Logo" /></a>
                    </div>
                    <div class="footer-container-right col-sm-4 col-md-4 text-right">
                        <p>село Крапец</p>
                        <a href="tel:@XmlHelper.GetNode("PhoneNumber")">тел: @XmlHelper.GetNode("PhoneNumber").BeautifyPhoneNumber()</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="footer-section-bottom">
            <div class="container">
                <div class="bottom row">
                    <div class="footer-social-icons col-sm-6">
                        <p>&copy; @DateTime.Now.Year - Крапец Холидей</p>
                    </div>
                    <div class="footer-author col-sm-6 text-right">
                        създаден от Paco
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @RenderSection("scripts", required: false)
</body>
</html>

Hotel.App/Views/Shared/_Messages.cshtml
@if (TempData.ContainsKey("message"))
{
    <div class="col-sm-offset-2 col-sm-8 alert alert-info global-message">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>@TempData["message"]</strong>
    </div>
}

Hotel.App/Views/Shared/_ReviewComment.cshtml
@model Hotel.App.Models.ViewModels.ReviewCommentViewModel

@using (Html.BeginForm("CreateComment", "Reviews"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="text-left"><i>напиши коментар</i></div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Content, "", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" name="reviewId" value="@Model.ReviewId" />

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Публикувай" class="btn btn-primary" />
            </div>
        </div>
    </div>
}