Hotel.App/Models/ViewModels/AppointmentViewModel.cs
namespace Hotel.App.Models.ViewModels
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class AppointmentViewModel
    {
        [Required(ErrorMessage = "Моля, въведете име")]
        [MinLength(3, ErrorMessage = "Името не може да е по-късо от 3 символа"), MaxLength(50, ErrorMessage = "Името не може да е по-дълго от 50 символа")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Моля, въведете фамилия")]
        [MinLength(3, ErrorMessage = "Фамилията не може да е по-къса от 3 символа"), MaxLength(50, ErrorMessage = "Фамилията не може да е по-дълга от 50 символа")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Моля, въведете имейл")]
        [EmailAddress(ErrorMessage = "Моля, въведете валиден имейл")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Моля, въведете телефон")]
        [RegularExpression("([\\d ]+)", ErrorMessage = "Моля, въведете валиден телефонен номер /само цифри/")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Моля, изберете брой")]
        [Range(1, 4, ErrorMessage = "Броят трябва да бъде между 1 и 4")]
        public int HosesCount { get; set; }

        [Required(ErrorMessage = "Моля, изберете начална дата")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "Моля, изберете крайна дата")]
        public DateTime EndDate { get; set; }

        public string Comment { get; set; }
    }
}

Hotel.App/Models/ViewModels/ControlPanelViewModel.cs
namespace Hotel.App.Models.ViewModels
{
    public class ControlPanelViewModel
    {
        public string ReviewsType { get; set; }

        public string ReviewsSortOrder { get; set; }

        public string ReviewContent { get; set; }

        public string AppointmentType { get; set; }

        public string AppointmentSortOrder { get; set; }
    }
}

Hotel.App/Models/ViewModels/ReviewCommentViewModel.cs
namespace Hotel.App.Models.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    public class ReviewCommentViewModel
    {
        [Required]
        [MinLength(10, ErrorMessage = "Коментарът трябва да е дълъг поне 10 символа")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }   

        [Required]
        public int ReviewId { get; set; }
    }
}

Hotel.App/Controllers/AppointmentController.cs
namespace Hotel.App.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Hotel.Models;
    using Models.ViewModels;
    using AutoMapper;
    using System.Net.Mail;
    using System.Threading.Tasks;
    using Utils;

    public class AppointmentController : BaseController
    {
        public AppointmentController(IHotelData data)
            : base(data)
        {
        }


        public ActionResult Index()
        {
            var appointments = this.Data.Appointments.All().ToList();

            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(AppointmentViewModel appointmentModel)
        {
            if (this.ModelState.IsValid)
            {
                this.ViewBag.IsDisabled = "disabled";

                var appointment = Mapper.Map<Appointment>(appointmentModel);

                this.Data.Appointments.Add(appointment);
                this.Data.SaveChanges();


                var message = new MailMessage();
                var toEmail = XmlHelper.GetNode("LeadsEmail");
                message.To.Add(new MailAddress(toEmail));
                message.Subject = "Имейл за резервация от Крапец Холидей";
                message.Body = this.FillClientInfo(appointmentModel);
                message.IsBodyHtml = true;

                using (var smtp = new SmtpClient())
                {
                    await smtp.SendMailAsync(message);
                }

                this.TempData["message"] = @"Резервацията Ви е изпратена успешно!
                                             Ще се свържем с Вас до 2 работни часа за потвърждение!";
                return this.View();
            }

            return this.View(appointmentModel);
        }

        private string FillClientInfo(AppointmentViewModel model)
        {
            var template = System.IO.File.ReadAllText(this.Server.MapPath("~/Files/Templates/AppointmentEmailTemplate.html"));
            template = template.Replace("[TEMPLATE_NAME]", model.FirstName).
            Replace("[TEMPLATE_LAST_NAME]", model.LastName).
            Replace("[TEMPLATE_EMAIL]", model.Email).
            Replace("[TEMPLATE_PHONE]", model.Phone).
            Replace("[TEMPLATE_START_DATE]", model.StartDate.ToString("dd.MM.yyyy")).
            Replace("[TEMPLATE_END_DATE]", model.EndDate.ToString("dd.MM.yyyy")).
            Replace("[TEMPLATE_COUNT]", model.HosesCount.ToString());

            return template;
        }
    }
}

Hotel.App/Controllers/ControlPanelController.cs
namespace Hotel.App.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using Models.ViewModels;
    using System.Data.Entity;
    using System.Resources;

    [Authorize(Roles ="Admin")]
    public class ControlPanelController : BaseController
    {
        public ControlPanelController(IHotelData data)
            : base(data)
        {
        }

        public ActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult ReviewsOption(ControlPanelViewModel model)
        {
            var type = model.ReviewsType;
            var order = model.ReviewsSortOrder;
            var content = model.ReviewContent;

            var reviews = this.Data.Reviews.All().Include(r => r.Comments).Include(r => r.Author);
            if (type == "published")
            {
                reviews = reviews.Where(r => r.IsPublished == true);
            }
            else if (type == "unpublished")
            {
                reviews = reviews.Where(r => r.IsPublished == false);
            }

            if (!string.IsNullOrEmpty(content))
            {
                reviews = reviews.Where(r => r.Content.Contains(content));
            }


            if (order == "ascending")
            {
                reviews = reviews.OrderBy(r => r.CreationDate);
            }
            else
            {
                reviews = reviews.OrderByDescending(r => r.CreationDate);
            }

            return this.View("Reviews", reviews.ToList());
        }

        [HttpPost]
        public ActionResult AppointmentsOption(ControlPanelViewModel model)
        {
            var type = model.AppointmentType;
            var order = model.AppointmentSortOrder;

            var appointments = this.Data.Appointments.All();
            if (type == "approved")
            {
                appointments = appointments.Where(r => r.IsApproved == true);
            }
            else if (type == "unapproved")
            {
                appointments = appointments.Where(r => r.IsApproved == false);
            }

            if (order == "ascending")
            {
                appointments = appointments.OrderBy(r => r.StartDate);
            }
            else
            {
                appointments = appointments.OrderByDescending(r => r.StartDate);
            }

            return this.View("Appointments", appointments.ToList());
        }

        [HttpPost]
        public ActionResult EditAppointment(string id, string isPublished)
        {
            int intId;
            bool isInt = int.TryParse(id, out intId);
            if (!isInt)
            {
                return this.HttpNotFound();
            }

            var appointment = this.Data.Appointments.Find(intId);
            appointment.IsApproved = isPublished != null;

            this.Data.SaveChanges();

            return this.PartialView("_Appointment", appointment);
        }


        [HttpPost]
        public ActionResult EditReview(string id, string isPublished)
        {
            int intId;
            bool isInt = int.TryParse(id, out intId);
            if (!isInt)
            {
                return this.HttpNotFound();
            }

            var review = this.Data.Reviews.Find(intId);
            review.IsPublished = isPublished != null;

            this.Data.SaveChanges();

            return this.PartialView("_Review", review);
        }

        [HttpPost]
        public ActionResult EditComment(string reviewId, string commentId, string isPublished)
        {
            int intReviewId;
            bool isInt = int.TryParse(reviewId, out intReviewId);
            if (!isInt)
            {
                return this.HttpNotFound();
            }

            var review = this.Data.Reviews.All().Include(r => r.Author).FirstOrDefault(r => r.Id == intReviewId);

            if (review == null)
            {
                return this.HttpNotFound();
            }

            var comment = review.Comments.FirstOrDefault(c => c.Id == int.Parse(commentId));

            if (comment == null)
            {
                return this.HttpNotFound();
            }

            comment.IsPublished = isPublished != null;

            this.Data.SaveChanges();

            return this.PartialView("_ReviewComment", comment);
        }

        public ActionResult EditSiteInfo()
        {
            var info = new SiteInfoViewModel();

            return this.View(info);
        }

        [HttpPost]
        public ActionResult EditSiteInfo(SiteInfoViewModel model)
        {
            return this.PartialView();
        }
    }
}

Hotel.App/Views/ControlPanel/Appointments.cshtml
@model IEnumerable<Hotel.Models.Appointment>

<h1 class="review-title text-center">Резервации</h1>

<div class="admin-appointments">
    @foreach (var review in Model)
    {
        @Html.Partial("_Appointment", review)
    }
</div>

@Scripts.Render("~/bundles/ajax")
@Scripts.Render("~/bundles/controlpanel")

Hotel.App/Views/ControlPanel/EditSiteInfo.cshtml
@model Hotel.App.Models.ViewModels.SiteInfoViewModel

<h1>Сайт инфо</h1>
<hr>

<div id="edit-siteinfo">
    @using (Ajax.BeginForm("EditSiteInfo", "ControlPanel", new AjaxOptions()
            {
                UpdateTargetId = "edit-siteinfo",
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                OnSuccess = "successUpdateSiteinfo()"
            }))
            {
        <div class="row">
            <div class="col-sm-3">
                @Html.LabelFor(model => model.LeadsEmail, "Имейл")
                @Html.TextBoxFor(model => model.LeadsEmail)
            </div>

            <div class="col-sm-3">
                @Html.LabelFor(model => model.FacebookUrl, "Фейсбук")
                @Html.EditorFor(model => model.FacebookUrl)
            </div>

            <div class="col-sm-3">
                @Html.LabelFor(model => model.GooglePlusUrl, "Гугъл")
                @Html.EditorFor(model => model.GooglePlusUrl)
            </div>

            <div class="col-sm-3">
                @Html.LabelFor(model => model.Skype, "Скайп")
                @Html.EditorFor(model => model.Skype)
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                @Html.LabelFor(model => model.PhoneNumber, "Телефон")
                @Html.EditorFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <input type="submit" value="Потвърди" class="btn btn-danger" />
            </div>
        </div>
       
        <span class="success-message" id="siteinfoSuccessMsg">Запазено!</span>
    }
</div>

@Scripts.Render("~/bundles/ajax")

Hotel.App/Views/ControlPanel/Index.cshtml
@model Hotel.App.Models.ViewModels.ControlPanelViewModel

<h1 class="text-left">Контролен панел</h1>

@using (Html.BeginForm("ReviewsOption", "ControlPanel", FormMethod.Post))
{
    <div class="form-horizontal admin-form">

        <h3>Отзиви</h3><hr />
        <div class="row">
            <div class="form-group col-sm-3">
                @Html.HiddenFor(m => m.ReviewsType)
                <label for="reviewType" class="col-xs-12">Състояние</label>
                <select id="reviewType">
                    <option value="published">Публикувани</option>
                    <option value="unpublished">Непубликувани</option>
                    <option value="all">Всички</option>
                </select>
            </div>

            <div class="form-group col-sm-3">
                @Html.HiddenFor(m => m.ReviewsSortOrder)
                <label for="reviewSorting" class="col-xs-12">Сортиране</label>
                <select id="reviewSorting">
                    <option value="ascending">Възходящо</option>
                    <option value="descending">Низходящо</option>
                </select>
            </div>

            <div class="form-group col-sm-3">
                @Html.LabelFor(m => m.ReviewContent, "Съдържание", new { @class = "col-xs-12" })
                @Html.EditorFor(m => m.ReviewContent)
            </div>

            <div class="form-group col-sm-3">
                <input type="submit" value="Потвърди" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("AppointmentsOption", "ControlPanel", FormMethod.Post))
{
    <div class="form-horizontal admin-form">

        <h3>Резервации</h3><hr />
        <div class="row">
            <div class="form-group col-sm-3">
                <label for="appType" class="col-xs-12">Състояние</label>
                <select id="appType">
                    <option value="approved">Публикувани</option>
                    <option value="unapproved">Непобликувани</option>
                    <option value="all">Всички</option>
                </select>
            </div>

            <div class="form-group col-sm-3">
                <label for="appSorting" class="col-xs-12">Сортиране</label>
                <select id="appSorting">
                    <option value="ascending">Възходящо</option>
                    <option value="descending">Низходящо</option>
                </select>
            </div>

            @Html.HiddenFor(m => m.AppointmentType)
            @Html.HiddenFor(m => m.AppointmentSortOrder)
            <div class="form-group col-sm-3">
                <input type="submit" value="Потвърди" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="row site-info-link">
    <h3>Сайт Инфо</h3><hr />
    <a href="/ControlPanel/EditSiteInfo" class="btn btn-danger">Редактирай</a>
</div>

@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/UI")

Hotel.App/Views/ControlPanel/Reviews.cshtml
@model IEnumerable<Hotel.Models.Review>

<h1 class="review-title text-center">Отзиви</h1>

@foreach (var review in Model)
{
    @Html.Partial("_Review", review)
}

@Scripts.Render("~/bundles/ajax")
@Scripts.Render("~/bundles/controlpanel")

Hotel.App/Views/ControlPanel/_Appointment.cshtml
@model Hotel.Models.Appointment

<div id="editAppointment@(Model.Id)">
    <div class="single-appointment">
        <div class="row">
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.FirstName, "Име")
                </div>
                @Html.DisplayTextFor(m => m.FirstName)
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.LastName, "Фамилия")
                </div>
                @Html.DisplayTextFor(m => m.LastName)
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.Email, "Имейл")
                </div>
                @Html.DisplayTextFor(m => m.Email)
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.Phone, "Телефон")
                </div>
                @Html.DisplayTextFor(m => m.Phone)
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.HosesCount, "Брой")
                </div>
                @Html.DisplayTextFor(m => m.HosesCount)
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.StartDtae, "От дата")
                </div>
                @Html.DisplayFor(m => m.StartDtae, "ShortDateTime")
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.EndDate, "До дата")
                </div>
                @Html.DisplayFor(m => m.EndDate, "ShortDateTime")
            </div>
            <div class="col-sm-3">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.CreationTime)
                </div>
                @Html.DisplayTextFor(m => m.CreationTime)
            </div>
        </div>

        <div class="row">
            <div class="col-sm-9">
                <div class="col-xs-12">
                    @Html.LabelFor(m => m.Comment, "Коментар")
                </div>
                @Html.DisplayTextFor(m => m.Comment)
            </div>
        </div>

        @using (Ajax.BeginForm("EditAppointment", "ControlPanel", new AjaxOptions()
        {
            UpdateTargetId = "editAppointment" + Model.Id,
            HttpMethod = "Post",
            InsertionMode = InsertionMode.Replace,
            OnSuccess = "success(" + Model.Id + ")"
        }))
        {
            <input name="id" type="hidden" value="@Model.Id">
            <label for="">Одобрен</label>
            <input checked="@Model.IsApproved" class="check-box" name="isPublished" type="checkbox" value="@Model.IsApproved">

            <input type="submit" value="Потвърди" class="btn btn-default" />
            <span class="success-message" id="entry@(Model.Id)">Потвърдено!</span>
        }
        <hr />
    </div>
</div>

Hotel.App/Views/ControlPanel/_Review.cshtml
@model Hotel.Models.Review

<div id="editReview@(Model.Id)">
    <div class="row single-review">

        <div class="col-sm-3 text-center author-info">
            <div class="review-author">@Model.Author.UserName</div>
            <div class="review-date">@Model.CreationDate</div>
            <div>@(Model.Rating)</div>
        </div>

        <div class="col-sm-9  text-left review-body">
            <div>@Model.Content</div>


            @using (Ajax.BeginForm("EditReview", "ControlPanel", new AjaxOptions()
            {
                UpdateTargetId = "editReview" + Model.Id,
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                OnSuccess = "success(" + Model.Id + ")"
            }))
            {
                <input name="id" type="hidden" value="@Model.Id">
                <label for="">Публикуван</label>
                <input checked="@Model.IsPublished" class="check-box" name="isPublished" type="checkbox" value="@Model.IsPublished">

                <input type="submit" value="Потвърди" class="btn btn-default" />
                <span class="success-message" id="entry@(Model.Id)">Успех!</span>
            }
            
        </div>
        <div class="col-md-8 col-sm-7  text-left review-body">
            @foreach (var comment in Model.Comments)
            {
                @Html.Partial("_ReviewComment", comment)
            }
        </div>
    </div>
</div>

Hotel.App/Views/ControlPanel/_ReviewComment.cshtml
@model Hotel.Models.ReviewComment

<div id="editComment@(Model.Review.Id)_@(Model.Id)">
    <div class="row single-comment">
        <div class="col-md-8 col-sm-7  text-left review-body">

            <div>@Model.Content</div>
            <div>@Model.Author.UserName</div>
            <div>@Model.CreationTime</div>

            @using (Ajax.BeginForm("EditComment", "ControlPanel", new AjaxOptions()
            {
                UpdateTargetId = "editComment" + Model.Review.Id + "_" + Model.Id,
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                OnSuccess = "success('" + Model.Review.Id + '_'  + Model.Id+ "')"
            }))
            {
                <input name="reviewId" type="hidden" value="@Model.Review.Id">
                <input name="commentId" type="hidden" value="@Model.Id">
                <label for="">Публикуван</label>
                    <input checked="@Model.IsPublished" class="check-box" name="isPublished" type="checkbox" value="@Model.IsPublished">

                    <input type="submit" value="Потвърди" class="btn btn-default" />
                    <span class="success-message" id="entry@(Model.Review.Id)_@(Model.Id)">Успех!</span>
            }

        </div>
    </div>
</div>